version: "3"
services:
  database:
    image: mysql
    container_name: linknamu_db
    env_file:
      - ./conf/mysql/.env
    ports:
      - "3306:3306"
    volumes:  #로컬 디비를 이용하기 위한 Volume 설정
      - ./conf/mysql/db:/var/lib/mysql
    networks:
      - spring-stage-network

  redis:
    image: redis:alpine
    container_name: redis_stage
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - spring-stage-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: web_stage
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    depends_on:
      - redis
      - database
    networks:
      - spring-stage-network

networks:
  spring-stage-network: