server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8000

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false

application:
  name: LinkNamuApplication

h2:
  console:
    enabled: true

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG

security:
  basic:
    enabled: false

access-jwt-secret-key: KakaoTechCampusLinkNamu
refresh-jwt-secret-key: KakaoTechCampusLinkNamu1234

cloud:
  aws:
    s3:
      bucket: linknamu-image
    credentials:
      access-key: test_access_key
      secret-key: test_secret_key
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


AES_SECRET_KEY: test_aes_secret_key
