
server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URI}
    username: root
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

    open-in-view: false


  application:
    name: LinkNamuApplication

  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG

access-jwt-secret-key: KakaoTechCampusLinkNamu
refresh-jwt-secret-key: KakaoTechCampusLinkNamu1234

oauth2:
  google:
    client_id : ${GOOGLE_CLIENT_ID}
    auth_uri : ${GOOGLE_AUTH_URI}
    token_uri : ${GOOGLE_TOKEN_URI}
    client_secret : ${GOOGLE_CLIENT_SECRET}
    redirect_uri : ${GOOGLE_REDIRECT_URI}

AES_SECRET_KEY: ${AES_SECRET_KEY}


