server:
  servlet:
    encoding:
      charset: utf-8
      force: true #  응답에 대해 UTF-8 문자 인코딩을 강제로 적용하게 됩니다.
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URI}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 100

    open-in-view: false


  application:
    name: LinkNamuApplication

  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    org.springframework: INFO
    com.example: INFO

proxy:
  enabled: true

oauth2:
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    client_secret: ${GOOGLE_CLIENT_SECRET}
    redirect_uri: ${GOOGLE_REDIRECT_URI}
  notion:
    client_id: ${NOTION_CLIENT_ID}
    secret: ${NOTION_SECRET}
    redirect_uri: ${NOTION_REDIRECT_URI}

cloud:
  aws:
    s3:
      bucket: linknamu-image
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

access-jwt-secret-key: ${ACCESS_JWT_SECRET_KEY}
refresh-jwt-secret-key: ${REFRESH_JWT_SECRET_KEY}

AES_SECRET_KEY: ${AES_SECRET_KEY}
